# Generated by Django 3.2.9 on 2022-01-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdate', models.DateTimeField(auto_now=True)),
                ('ccustomer', models.CharField(max_length=20)),
                ('camount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('bname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.brand')),
            ],
            options={
                'unique_together': {('bname', 'name', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_customer', models.CharField(max_length=20)),
                ('sdate', models.DateTimeField(auto_now=True)),
                ('srate', models.FloatField(default=0.0)),
                ('squantity', models.IntegerField(default=0)),
                ('discounttype', models.CharField(max_length=10)),
                ('discount', models.FloatField(default=0.0)),
                ('sprice', models.FloatField(default=0.0)),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdate', models.DateTimeField(auto_now=True)),
                ('prate', models.FloatField(default=0.0)),
                ('pquantity', models.IntegerField(default=0)),
                ('pnotes', models.CharField(max_length=1000)),
                ('pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.product')),
            ],
        ),
    ]
